# Generated by Django 3.2 on 2021-05-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='to_SI_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
