# Generated by Django 3.2 on 2021-05-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_to_si_unit'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
    ]
